### ISSUE TITLE
找不到 127.0.0.1 的网页

### ISSUE THREAD

**Issue by lgcxc** [jrainlau/tiny-reactive#1]
![image](https://user-images.githubusercontent.com/15682051/66752976-51366c80-eec5-11e9-8c33-234245ad465a.png)
![image](https://user-images.githubusercontent.com/15682051/66752996-5a273e00-eec5-11e9-9e6d-e1d47b1fe22b.png)
这是啥情况呢？

**Comment by jermyn626** [comment]
😮看 [README](https://github.com/jrainlau/tiny-reactive/blob/master/README.md)，没有 `dev reactivity` 这个命令

```
# 1
yarn install

# 2
yarn dev  
```

**Comment by myfatherisa** [comment]
![image](https://user-images.githubusercontent.com/24894296/67070197-f7c68a00-f1b1-11e9-9417-9ec8987b81e7.png)
那么，这是啥情况呢？

**Comment by jermyn626** [comment]
@myfatherisa 试一下访问 `/index`

**Comment by myfatherisa** [comment]
![image](https://user-images.githubusercontent.com/24894296/67071256-a66bca00-f1b4-11e9-83cb-5f6387fb2a42.png)
多谢。已经解决了。
